name: Options tests with docker build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Calculate version
        env:
          TAG: ${{ github.ref_name }}
        id: version
        run: echo "::set-output name=version::${TAG##*.}"
        
      - name: Build and run Docker Image
        run: |
          echo ${{ steps.version.outputs.version }}