name: Options tests with docker build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Build and run Docker Image
        run: |
          echo ${${{ github.ref_name }}##*.}